title: Welcome
description: > # this means to ignore newlines until "baseurl:"
  I am Munim Hasan Wasi.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Munim Hasan Wasi # add your name
author-img: mhw2.png # add your photo
about-author: I am an undergraduate student at KAIST majoring in Computer Science and minoring in Economics # add description
social-twitter: aidanhere91 # add your Twitter handle
social-facebook: aidanhere91 # add your Facebook handle
social-github: aidanhere # add your Github handle
social-linkedin: aidanhere # add your Linkedin handle
social-email: aidan@kaist.ac.kr # add your Email address

# Disqus
discus-identifier: #aidanhere # add your discus identifier

# Tracker
analytics: G-TZ5WLQF8VM # Google Analytics
google_analytics: G-TZ5WLQF8VM

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
